/*
 * See zynq_common.h for Zynq common configs
 */

#ifndef __CONFIG_NIMYRIO_H
#define __CONFIG_NIMYRIO_H

/*
 * High Level Configuration Options
 */
#define CONFIG_NIMYRIO /* Board */
#ifdef CONFIG_BOARD_ONLY
#define CONFIG_DEVICE_CODE "76D3"
#define CONFIG_FPGA_DEVICE_CODE "76D3"
#define CONFIG_DEVICE_DESC "myRIO-1950"
#else
#ifdef CONFIG_ROBORIO
#define CONFIG_DEVICE_CODE "76F2"
#define CONFIG_FPGA_DEVICE_CODE "77A9"
#define CONFIG_DEVICE_DESC "roboRIO"
#else
#define CONFIG_DEVICE_CODE "762F"
#define CONFIG_FPGA_DEVICE_CODE "762F"
#define CONFIG_DEVICE_DESC "myRIO-1900"
#endif
#endif
#define CONFIG_TARGET_CLASS "cRIO"
#define CONFIG_PREFIXED_DEVICE_DESC "NI " CONFIG_DEVICE_DESC

/* For all myRIOs, pretend to be the packaged myRIO over USB */
#define CONFIG_NI_USB_PID "0x762F"
#define CONFIG_NI_USB_VID "0x3923"

#define CONFIG_CPU_FREQ_HZ 666666666

#include <configs/zynq_common.h>

#undef CONFIG_ZYNQ_XIL_LQSPI

#define CONFIG_SYS_NO_FLASH

#include <config_cmd_default.h>
#undef CONFIG_CMD_XIMG
#define CONFIG_FIT
#define CONFIG_OF_BOARD_SETUP
#define CONFIG_CMD_DATE		/* RTC? */
#define CONFIG_CMD_PING		/* Might be useful for debugging */
#define CONFIG_REGINFO		/* Again, debugging */
#undef CONFIG_CMD_SETGETDCR	/* README says 4xx only */
/* check for input to stop even if delay is 0 */
#define CONFIG_ZERO_BOOTDELAY_CHECK
#undef CONFIG_BOOTDELAY
/* -1 to Disable autoboot, -2 to force boot */
#define CONFIG_BOOTDELAY	-2
#define CONFIG_SILENT_CONSOLE
#define CONFIG_SILENT_U_BOOT_ONLY
#define CONFIG_SILENT_CONSOLE_UPDATE_ON_SET
#define CONFIG_SYS_DEVICE_NULLDEV
#define CONFIG_BAUDRATE_UPDATE_ON_RELOC

#define CONFIG_SYS_LONGHELP
#define CONFIG_SYS_HUSH_PARSER
#define CONFIG_SYS_PROMPT_HUSH_PS2 "hush> "
#undef CONFIG_SYS_MAXARGS
#define CONFIG_SYS_MAXARGS 64

#define CONFIG_CMD_UNZIP
#define CONFIG_CMD_SETEXPR
#define CONFIG_CRC32_VERIFY
#define CONFIG_CMD_MD5SUM
#define CONFIG_MD5SUM_VERIFY
#define CONFIG_CMD_SHA1SUM
#define CONFIG_SHA1SUM_VERIFY
#define CONFIG_CMD_INI
#define CONFIG_INI_CASE_INSENSITIVE

#define CONFIG_TIMESTAMP	/* print image timestamp on bootm, etc */

#if defined(CONFIG_ROBORIO)
#define CONFIG_NI_BOARD_NAME "roboRIO"
#else
#define CONFIG_NI_BOARD_NAME "myRIO"
#endif

#ifdef CONFIG_MFG
#define CONFIG_NI_BOARD_NAME_SUFFIX " Manufacturing"
#else
#define CONFIG_NI_BOARD_NAME_SUFFIX
#endif

#define CONFIG_NI_BOARD_NAME_PREFIX

#define CONFIG_IDENT_STRING \
	"\nNational Instruments" \
	CONFIG_NI_BOARD_NAME_PREFIX " " \
	CONFIG_NI_BOARD_NAME \
	CONFIG_NI_BOARD_NAME_SUFFIX

#undef CONFIG_SYS_PROMPT
#define CONFIG_SYS_PROMPT	"U-Boot> "

#define CONFIG_AUTO_COMPLETE
#define CONFIG_CMDLINE_EDITING

#define CONFIG_ENV_IS_IN_UBI
#define CONFIG_ENV_UBI_PART "boot-config"
#define CONFIG_ENV_UBI_VOLUME "u-boot-env1"
#define CONFIG_ENV_UBI_VOLUME_REDUND "u-boot-env2"
#undef CONFIG_ENV_SIZE
#define CONFIG_ENV_SIZE			0x20000

#define CONFIG_CMD_SAVEENV	/* Command to save ENV to Flash */
#define CONFIG_CMD_ENV_FLAGS

#define CONFIG_FPGA
#define CONFIG_FPGA_XILINX
#define CONFIG_FPGA_ZYNQPL
#define CONFIG_CMD_FPGA

/* HW to use */
#define CONFIG_SERIAL_MULTI
#undef CONFIG_ZYNQ_SERIAL
#define CONFIG_CONSOLE_LINUX_DEV "ttyS0"
#define CONFIG_CONSOLE_UBOOT_DEV "eserial0"
#ifdef CONFIG_ROBORIO
#define CONFIG_ZYNQ_UART0
#define CONFIG_ZYNQ_SERIAL
#endif
#define CONFIG_SYS_NS16550
#define CONFIG_SYS_NS16550_SERIAL
#define CONFIG_SYS_NS16550_CLK 58824000
#define CONFIG_SYS_NS16550_REG_SIZE 1
#define CONFIG_SYS_NS16550_COM1 0x80000000
#define CONFIG_SYS_NS16550_COM2 0x80000010
#define CONFIG_CONS_INDEX 1 /* not actually used */

#ifdef CONFIG_ROBORIO
/* Use GEM0 */
#define CONFIG_NET_MULTI
#define CONFIG_ZYNQ_GEM
#define CONFIG_ZYNQ_GEM_COUNT	1

/* GEM0 on EMIO */
#define CONFIG_ZYNQ_GEM0_EMIO
#define CONFIG_ZYNQ_GEM0_BASE_ADDR	XPSS_GEM0_BASEADDR
#define CONFIG_ZYNQ_GEM0_PHY_ADDR	0
#define CONFIG_ZYNQ_GEM0_LINK_SPEED_100_GPIO 54
#define CONFIG_ZYNQ_GEM0_LINK_SPEED_100_GPIO_ON 1
#define CONFIG_ZYNQ_GEM0_LINK_SPEED_100_GPIO_OFF 0

#define CONFIG_CMD_MII
#define CONFIG_MII
#endif /* CONFIG_ROBORIO */

#define CONFIG_CMD_DHCP
#define CONFIG_CMD_LINK_LOCAL
#define CONFIG_BOOTP_MAY_FAIL
#define CONFIG_BOOTP_SERVERIP
#define CONFIG_BOOTP_SUBNETMASK
#define CONFIG_BOOTP_GATEWAY
#define CONFIG_BOOTP_DNS
#define CONFIG_BOOTP_HOSTNAME
#define CONFIG_BOOTP_SEND_HOSTNAME
#define CONFIG_NETCONSOLE

#ifdef CONFIG_MFG
#define CONFIG_RANDOM_MACADDR
#endif

#ifdef CONFIG_ROBORIO
#define CONFIG_ZYNQ_GPIO
#endif

#define CONFIG_CMD_I2C
/* not really used */
#define CONFIG_SYS_I2C_SPEED 400
#define CONFIG_HARD_I2C
#define CONFIG_ZYNQ_I2C
#define CONFIG_ZYNQ_I2C_CTLR_0

/* USB Host support */
#define CONFIG_CMD_USB
#define CONFIG_USB_HOST
#define CONFIG_USB_STORAGE
#define CONFIG_CMD_FAT
#define CONFIG_DOS_PARTITION
#define CONFIG_USB_HOST_ETHER
#define CONFIG_USB_ETHER_ASIX
#define CONFIG_USB_ETHER_SMSC95XX
#define CONFIG_USB_ULPI
#define CONFIG_USB_ULPI_VIEWPORT
#define CONFIG_USB_EHCI
#define CONFIG_USB_EHCI_ZYNQ
#define CONFIG_USB_EHCI_TXFIFO_THRESH 8
#define CONFIG_EHCI_IS_TDI
#define CONFIG_USB_BASE_ADDR XPSS_USB0_BASEADDR

/*
 * Physical Memory map
 */
#define PHYS_SDRAM_1_SIZE (256 * 1024 * 1024)
#define CONFIG_SYS_ALT_MEMTEST
#define CONFIG_SYS_MEMTEST_SCRATCH 0xFFFFF000
#define CONFIG_CMD_CACHE

/*
 * NAND Flash settings
 */
#define CONFIG_NAND_ZYNQ
#define CONFIG_NAND_ZYNQ_USE_FSBL_TIMINGS
#define CONFIG_CMD_NAND
#define CONFIG_CMD_NAND_LOCK_UNLOCK
#define CONFIG_SYS_MAX_NAND_DEVICE 1
#define CONFIG_SYS_NAND_ONFI_DETECTION
#define CONFIG_SYS_NAND_BASE XPSS_NAND_BASEADDR
#define CONFIG_SYS_NAND_SELF_INIT
#define CONFIG_MTD_DEVICE
#define CONFIG_MTD_PARTITIONS
#define CONFIG_MTD_RESERVE_END 524288
#define CONFIG_CMD_MTDPARTS
#define MTDIDS_DEFAULT "nand0=xilinx_nand"
#define MTDPARTS_DEFAULT \
	"mtdparts=xilinx_nand:" \
		"128k(fsbl)ro," \
		"11M(u-boot)ro," \
		"70M(boot-config)," \
		"-(root)"

#if defined(CONFIG_MFG)
#define CONFIG_NAND_BBT_NO_MARK
#endif

/* UBI */
#define CONFIG_RBTREE
#define CONFIG_CMD_UBI

/* UBIFS */
#define CONFIG_LZO
#define CONFIG_CMD_UBIFS

#define CONFIG_MTD_UBOOT_OFFSET		0x20000
#define CONFIG_BOARD_SIZE_LIMIT		0x100000
#define CONFIG_BOOT_BIN_SIZE_LIMIT	0x120000
#define CONFIG_BOOTFS_VOLUME_SIZE	0x3600000

#define CONFIG_BACKUP_PAGE		0xB1F800
#define CONFIG_BACKUP_USBGADGETETHADDR_OFFSET	0x7ea
#define CONFIG_BACKUP_SERIAL_OFFSET	0x7f0
#define CONFIG_BACKUP_ETHADDR_OFFSET	0x7f4
#define CONFIG_BACKUP_ETH1ADDR_OFFSET	0x7fa

#define CONFIG_DEFAULT_NVS "begin-base64 444 /lib/firmware/ti-connectivity/wl1271-nvs.bin.gz`H4sICK4CAAAAA3dsMTI3MS1udnMuYmluAGPMDWEAAsZCMIUAjDMZv0OZzP+/`/2PAA57/YWVn5+Tm5RcWkZBWUmXQZzBksGBwYvBkCGCIYohhiGdIYIhg8Mdn`xIgGf//9+w+kGCGACA1MwthEVzEDzWD6DzSKiZUBbB4DJ4uEAAfD9/fP74ME`+O1R+QwM6HwgePONgUfixx8GDoEPPxi4RCj0GgiUMzYwyMorqalrSskrqaqq`i8nKKaioBuABjExAwCAqKiooKsonp0sFNwwdAACjiUGVkAMAAA==`====`"

#undef CONFIG_SYS_LOAD_ADDR
#define CONFIG_SYS_LOAD_ADDR 0x4000000
#define CONFIG_LOADADDR CONFIG_SYS_LOAD_ADDR

#define FDT_HIGH "0x7FFFFFF"
#define INITRD_HIGH "0x7FF7FFF"
#define VERIFY_ADDR "0x8000000"

#include "niresetenv.h"

#if defined(CONFIG_MYRIO)

/* myRIO uses ethaddr for the USB Gadget Ethernet MAC. */
#define USBGADGETETHADDR_SAVE ENV_SAVE(ethaddr)
#define USBGADGETETHADDR_RESTORE ENV_RESTORE(ethaddr)

/* myRIO uses eth1addr for the WiFi Ethernet MAC. */
#define WIFIETHADDR_SAVE ENV_SAVE(eth1addr)
#define WIFIETHADDR_RESTORE ENV_RESTORE(eth1addr)

/* myRIO doesn't have wired Ethernet. */
#define ETHADDR_SAVE
#define ETHADDR_RESTORE

/* myRIO has a wl12xx */
#define WL12XXNVS_SAVE ENV_SAVE(wl12xxnvs)
#define WL12XXNVS_RESTORE ENV_RESTORE(wl12xxnvs)

#elif defined(CONFIG_ROBORIO)

/* roboRIO uses usbgadgetethaddr for the USB Gadget Ethernet MAC. */
#define USBGADGETETHADDR_SAVE ENV_SAVE(usbgadgetethaddr)
#define USBGADGETETHADDR_RESTORE ENV_RESTORE(usbgadgetethaddr)

/* roboRIO doesn't have WiFi. */
#define WIFIETHADDR_SAVE
#define WIFIETHADDR_RESTORE

/* roboRIO uses ethaddr for wired Ethernet. */
#define ETHADDR_SAVE ENV_SAVE(ethaddr)
#define ETHADDR_RESTORE ENV_RESTORE(ethaddr)

/* roboRIO does not have a wl12xx */
#define WL12XXNVS_SAVE
#define WL12XXNVS_RESTORE

#endif

#include "nicommonenv.h"

#define CONFIG_ENV_FLAGS_LIST_STATIC \
	READONLY_DEFAULT_ENV_FLAGS \
	READONLY_MFG_ENV_VARS \
	NET_TYPE_ENV_VARS

#if defined(CONFIG_MFG)

#undef CONFIG_EXTRA_ENV_SETTINGS
#define CONFIG_EXTRA_ENV_SETTINGS \
	"serverip=192.168.1.185\0" \
	REAL_EXTRA_ENV_SETTINGS

#undef CONFIG_BOOTCOMMAND

#define CONFIG_PREBOOT \
	"dcache off; " \
	"usb start; " \
	"usb reset; " \
	"dhcp; " \
	"run nc; " \
	"setenv silent;"

#else /* !CONFIG_MFG */

#undef CONFIG_EXTRA_ENV_SETTINGS
#define CONFIG_EXTRA_ENV_SETTINGS \
	REAL_EXTRA_ENV_SETTINGS

#undef CONFIG_BOOTCOMMAND
#define CONFIG_BOOTCOMMAND \
	REAL_BOOTCOMMAND

#define CONFIG_PREBOOT \
	REAL_PREBOOT

#endif

#endif /* __CONFIG_NIMYRIO_H */
